# inflator.toml syntax documentation: https://github.com/inflated-goboscript/inflator#inflator
name = "rosetta"
version = "v0.0.0"
username = "if this is left blank then -9999 aura 💀"

[dependencies]
